### ISSUE TITLE
Too more week

### ISSUE THREAD

**Issue by florentsorel** [kmdwebdesigns/calendar#1]
I think the behavior is weird for the calendar 2017-05

![image](https://cloud.githubusercontent.com/assets/1011503/24976621/7d48ed10-1fca-11e7-93a3-a7457caf0264.png)

Why the last week is displayed? In this case we don't need that week because in the previous one contains the last day for the current month.

**Comment by florentsorel** [comment]
Same thing for June, August 2017 (the first week of september - from 3 to 9 - is displayed and it's not necessary)

![image](https://cloud.githubusercontent.com/assets/1011503/24977747/5e45d47e-1fce-11e7-9381-a22155ba84b9.png)

**Comment by mikemand** [comment]
Hi @florentsorel,

I am looking at this now. I will see if I can make the number of weeks variable, depending on how many are truly necessary.

If I cannot fix this, what are your thoughts on keeping a static number of weeks in the calendar? I personally like to always see 6 weeks, it keeps my designs the same height no matter what month the calendar is showing.

**Comment by florentsorel** [comment]
If you cannot fix this, I think it's not a real problem here. I've checked my calandar on Linux Mint and 6 weeks are displayed, so... not a problem at all. But if you can add a setter (like setAdjustWeek(bool)) in `Calendar` class for adjusting the number of week automaticaly it can be good for people who want more config.

So if you don't know how to fix this issue, you can close it ;)

**Comment by mikemand** [comment]
Hi @florentsorel,

I think I did it. :D Can you try `^1.1` and let me know? You can enable the option like so:

```php
$calendar = new Calendar(2017, 5).
$calendar->setVariableWeeks(true);
```

You should see only 5 weeks, instead of 6.

**Comment by florentsorel** [comment]
I think the old bug https://github.com/carvefx/calendar/issues/3 is back or something similar :/

For April 2017 the all first week of May is displayed (1,2,3,4,5,6,7 May)
For May 2017 it seems to be working
For October 2017, 30 and 31 are missing

**Comment by mikemand** [comment]
Hi @florentsorel,

I will give it another attempt tomorrow. I'm not sure why it would be doing that, other than maybe it is not using the correct "first day".

**Comment by mikemand** [comment]
Good morning @florentsorel,

Could you give `v1.1.1` a try and let me know if it fixes the problem? It looks like it did for me:

`Carbon::setWeekStartsAt(Carbon::SUNDAY)`
![screen shot 2017-04-13 at 10 17 55 am](https://cloud.githubusercontent.com/assets/745184/25014250/2b459ea4-2034-11e7-9729-efb15db4ef9f.png)

`Carbon::setWeekStartsAt(Carbon::MONDAY)`
![screen shot 2017-04-13 at 10 20 48 am](https://cloud.githubusercontent.com/assets/745184/25014251/2b46257c-2034-11e7-8dd7-a97b35706ab4.png)

**Comment by florentsorel** [comment]
Hey, sorry for the delay. It seems to be working now ;)

**Comment by mikemand** [comment]
That's great news! Thank you for your patience with me. :)
